[project]
name = "schaakstudiespinsels2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.0",
    "llm>=0.27.1",
    "matplotlib>=3.10.3",
    "nbformat>=4.2.0",
    "opencv-python>=4.12",
    "pandas>=2.3.1",
    "python-chess>=1.999",
    "plotly>=6.3.1",
    "pymupdf>=1.26.5",
    "python-docx>=1.1.0",
    "rich>=14.1.0",
    "seaborn>=0.13.2",
    "unidecode>=1.4.0",
]
