"""One-shot: convert content/pages/*.md (Pelican) to src/content/pages/nl/*.md (Astro).

Rewrites the `Title: X\nPageorder: NNN` header block into YAML frontmatter and drops
files into the Astro content collection. Emits `src/content/pages/en/*.md` stubs
pointing at the Dutch original via `translationOf:` so the language toggle never
dead-ends. Skips `manke_maljutkas/` (that's the old Pelican-era study prototype;
studies are regenerated by parse_study.py).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "content" / "pages"
DST_NL = ROOT / "src" / "content" / "pages" / "nl"
DST_EN = ROOT / "src" / "content" / "pages" / "en"

HEADER_RE = re.compile(r"^(?P<k>[A-Za-z]+):\s*(?P<v>.*)$")


def parse_pelican_header(text: str) -> tuple[dict[str, str], str]:
    """Split a Pelican-style `Key: Value` header from the body.

    Uses plain `\\n` splitting (not `splitlines()`) because several of the
    source files contain embedded form-feed / vertical-tab bytes that
    `splitlines()` would treat as line breaks and corrupt the header.
    """
    # Scrub stray control characters from header values — they're artefacts of
    # the original Word → text → Markdown conversion and carry no meaning.
    text = text.replace("\f", "").replace("\v", "")
    lines = text.split("\n")
    headers: dict[str, str] = {}
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            break
        m = HEADER_RE.match(line)
        if not m:
            break
        headers[m["k"]] = m["v"].strip()
        i += 1
    # Skip the blank separator line
    while i < len(lines) and not lines[i].strip():
        i += 1
    return headers, "\n".join(lines[i:]).rstrip() + "\n"


def yaml_escape(s: str) -> str:
    # Titles like "- 1 -" and "You feel at ease..." — single-quote and double-up
    # any embedded single quotes, which is YAML's safe rule.
    return "'" + s.replace("'", "''") + "'"


def port_one(md: Path) -> None:
    headers, body = parse_pelican_header(md.read_text(encoding="utf-8"))
    if "Title" not in headers or "Pageorder" not in headers:
        print(f"skip (no Title/Pageorder): {md}", file=sys.stderr)
        return

    title = headers["Title"]
    order = int(headers["Pageorder"])
    slug = md.stem

    nl_fm = (
        "---\n"
        f"title: {yaml_escape(title)}\n"
        f"order: {order}\n"
        "---\n\n"
    )
    (DST_NL / f"{slug}.md").write_text(nl_fm + body, encoding="utf-8")

    en_fm = (
        "---\n"
        f"title: {yaml_escape(title)}\n"
        f"order: {order}\n"
        f"translationOf: {yaml_escape(f'nl/{slug}')}\n"
        "---\n\n"
        "*Translation in progress.*\n"
    )
    (DST_EN / f"{slug}.md").write_text(en_fm, encoding="utf-8")
    print(f"ported: {slug}")


def main() -> None:
    DST_NL.mkdir(parents=True, exist_ok=True)
    DST_EN.mkdir(parents=True, exist_ok=True)
    for md in sorted(SRC.glob("*.md")):
        port_one(md)


if __name__ == "__main__":
    main()
